<?php
/**
 * Implements hook_menu().
 */
function mypage_menu()
{

    $items['mypage'] = array(
        'title' => 'Welcome to my site Drupal 7 =)',
        'page callback' => 'main_page_content',
        'access callback' => TRUE,
        'menu_name' => 'mypage',
        'file' => 'mypage.inc',
        'options' => array('attributes' => array('class' => array('test-class'))),
    );


    $items['not_found'] = array(
        'title' => 'Sorry, this page does not exist =(',
        'page callback' => 'page_not_found',
        'access callback' => TRUE,
        'menu_name' => 'not_found',
        'file' => 'mypage.inc',
        'options' => array('attributes' => array('class' => array('test-class'))),
    );

    $items['denied'] = array(
        'title' => 'You are not right!',
        'page callback' => 'access_denied',
        'access callback' => TRUE,
        'menu_name' => 'denied',
        'file' => 'mypage.inc',
        'options' => array('attributes' => array('class' => array('test-class'))),
    );
    return $items;
}